// Code generated by "stringer -type DataType"; DO NOT EDIT.

package main

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[INTEGER-0]
	_ = x[DECIMAL-1]
	_ = x[FLOAT-2]
	_ = x[STRING-3]
	_ = x[DATE-4]
	_ = x[TIMESTAMP-5]
	_ = x[BOOLEAN-6]
}

const _DataType_name = "INTEGERDECIMALFLOATSTRINGDATETIMESTAMPBOOLEAN"

var _DataType_index = [...]uint8{0, 7, 14, 19, 25, 29, 38, 45}

func (i DataType) String() string {
	if i < 0 || i >= DataType(len(_DataType_index)-1) {
		return "DataType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _DataType_name[_DataType_index[i]:_DataType_index[i+1]]
}
